# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-16 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormBaseLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(default='form_group', max_length=255)),
                ('if_formset', models.BooleanField(default=False)),
                ('slug', models.SlugField(default='abc')),
            ],
        ),
        migrations.CreateModel(
            name='FormLevelOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_formset', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FormLevelThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FormLevelTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('if_formset', models.BooleanField(default=False)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynaform.FormLevelThree')),
            ],
        ),
        migrations.CreateModel(
            name='LegalDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='LegalQuestionaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LegalTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='docx-templates/')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.IntegerField(choices=[(0, 'textfield'), (1, 'charfield'), (2, 'boolean'), (3, 'integer')])),
                ('questionaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynaform.LegalQuestionaire')),
            ],
        ),
        migrations.AddField(
            model_name='formleveltwo',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynaform.LegalQuestionaire'),
        ),
        migrations.AddField(
            model_name='formlevelthree',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynaform.LegalQuestionaire'),
        ),
        migrations.AddField(
            model_name='formlevelone',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynaform.FormLevelTwo'),
        ),
        migrations.AddField(
            model_name='formlevelone',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynaform.LegalQuestionaire'),
        ),
        migrations.AddField(
            model_name='formbaselevel',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynaform.FormLevelOne'),
        ),
        migrations.AddField(
            model_name='formbaselevel',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynaform.LegalQuestionaire'),
        ),
    ]
