# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-26 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynaform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formlevelone',
            name='id',
        ),
        migrations.RemoveField(
            model_name='formlevelone',
            name='label',
        ),
        migrations.RemoveField(
            model_name='formleveltwo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='formleveltwo',
            name='label',
        ),
        migrations.AddField(
            model_name='formlevelone',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynaform.FormLevelTwo'),
        ),
        migrations.AddField(
            model_name='formlevelone',
            name='form_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='formlevelone',
            name='form_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynaform.LegalQuestionaire'),
        ),
        migrations.AddField(
            model_name='formlevelone',
            name='if_formset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formleveltwo',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynaform.FormLevelThree'),
        ),
        migrations.AddField(
            model_name='formleveltwo',
            name='form_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='formleveltwo',
            name='form_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynaform.LegalQuestionaire'),
        ),
        migrations.AddField(
            model_name='formleveltwo',
            name='if_formset',
            field=models.BooleanField(default=False),
        ),
    ]
