# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-12 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynaform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='LegalTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='docx-templates/')),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='field_type',
            field=models.IntegerField(choices=[(0, 'textfield'), (1, 'charfield'), (2, 'boolean'), (3, 'file')]),
        ),
    ]
