# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-10 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynaform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formbaselevel',
            name='if_formset',
        ),
        migrations.RemoveField(
            model_name='formlevelone',
            name='if_formset',
        ),
        migrations.RemoveField(
            model_name='formleveltwo',
            name='if_formset',
        ),
        migrations.AddField(
            model_name='formbaselevel',
            name='is_formset',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formlevelone',
            name='is_formset',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formlevelthree',
            name='is_formset',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formleveltwo',
            name='is_formset',
            field=models.BooleanField(default=True),
        ),
    ]
