# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-29 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dynaform', '0003_auto_20160517_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='legaldocuments',
            name='group',
            field=models.CharField(default='form_group', max_length=255),
        ),
        migrations.AddField(
            model_name='legaldocuments',
            name='slug',
            field=models.SlugField(default='abc', editable=False),
        ),
        migrations.AddField(
            model_name='legaldocuments',
            name='unique_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='legaltemplates',
            name='slug',
            field=models.SlugField(default='abc', editable=False),
        ),
        migrations.AlterField(
            model_name='questions',
            name='field_type',
            field=models.IntegerField(choices=[(0, 'textfield'), (1, 'charfield'), (2, 'boolean'), (3, 'integer'), (4, 'select')]),
        ),
    ]
